[profile.default]
libs = ['lib']
test = 'test'
auto_detect_solc = true
# Require read access for 'addresses' and 'out' folder on root repo for bytecode verification
fs_permissions = [{ access = "read", path = "./addresses/11155111.json"}]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "https://rpc.buildbear.io/sanam"
mainnet = "https://virtual.mainnet.rpc.tenderly.co/0391d9fa-0553-482f-9dac-6eb34f75001c" 

[fmt]
line_length = 80

#[etherscan]
#sepolia = { key = "verifyContract" }

